src/main/resources/assets/js/app/inputtype/ui/text/HtmlEditor.ts
src/main/resources/assets/lib/ckeditor/plugins/table/dialogs/table.js
src/main/resources/assets/lib/ckeditor/plugins/tableresize/plugin.js
src/main/resources/assets/lib/ckeditor/plugins/tabletools/dialogs/tableCell.js

-added missing dialogs for table and tabletools plugins
-added tableresize plugin
-brought back table context menu items: cell properties and table properties
NB: cell properties and table properties dialogs are native cke's dialogs, will need to add our versions of these modal dialogs

Improve table features in the HTML Editor

---

src/main/resources/assets/js/app/inputtype/text/HtmlArea.ts
src/main/resources/assets/js/app/inputtype/ui/siteconfigurator/SiteConfiguratorDialog.ts
src/main/resources/assets/js/app/inputtype/ui/text/HtmlEditor.ts

-we used to stop cke native blur event, that seems to prevent cke's handlers to finalize it's routine; now not stopping blur event
-destroying cke instance after element is already removed has no sense because destroy supposed to be invoked before element removed from dom; also that seems to bring errors in siteconfigurator dialog

CKEditor: Newly opened Link dialog shows old values #44

---

src/main/resources/assets/js/app/inputtype/ui/text/HtmlEditor.ts

-Made formatting shortcuts work
-disabled indent/outdent shortcut to make TAB key focus on next element on windows;
now indent/outdent commands executed only via buttons on toolbar

HTML Editor: Fix shortcut for heading and tab cycle

---

src/main/resources/assets/js/app/inputtype/ui/text/HtmlEditor.ts

-Editor's change event (after uploading image) might be fired before uploaded handler, so change handler doesn't see uploaded image yet.
Solved by triggering change event ourselves after image upload.

An image added via DnD won't get saved in a new HTML Area content #186

---

src/main/resources/assets/js/app/view/context/ContextSplitPanel.ts
src/main/resources/assets/js/app/view/context/ContextView.ts
src/main/resources/assets/js/app/wizard/ContentWizardPanel.ts
src/main/resources/assets/js/app/wizard/page/LiveFormPanel.ts
src/main/resources/assets/page-editor/styles/partials/page-view.less
src/main/resources/assets/styles/view/context/context-panel.less
src/main/resources/assets/styles/view/mobile-content-item-statistics-panel.less
src/main/resources/assets/styles/wizard/content-wizard-panel.less

* Fixed the presence of the Emulator in the wizard, when content is not renderable.
* Fixed the `z-index` of the context panel, making it render behind the toolbar.
* Updated context panel, disabling components and emulator in the wizard when page editor is not visible.
**Depends on PR #196.**

Incorrect number of widgets in the context panel #198

---

src/main/resources/assets/js/app/wizard/ContentWizardPanel.ts
src/main/resources/assets/js/app/wizard/page/LiveFormPanel.ts

Disabled context panel auto-expand on startup from small screens (smaller than 1920).

The Context panel auto-expands in the Wizard #242

---

src/main/resources/assets/js/page-editor/ItemViewContextMenu.ts

* Updated context menu to reposition, when it's expanded or collapsed.
* Refactored constructor.

Page Components View - context menu is cut off after expanding sub-menu #254

---

src/main/resources/assets/js/app/wizard/ContentWizardPanel.ts

Disabled `liveEditModel` update for content without the page editor.

Error in console after publishing a shortcut with an image in target #260

---

src/main/resources/assets/styles/view/context/context-panel.less

* Updated transition to be applied to the sliding (`right`) only.
* Updated position of the floating panel, when the upper container is blurred, since 
> ... value other than none for the filter property results in the creation of a containing block for absolute and fixed positioned descendants.
Thus, the position of the floating panel must be adjusted.

Floating context panel is shifted down whenever modal dialog opens #290

---

src/main/resources/assets/js/app/wizard/page/contextwindow/ContextWindow.ts

* Updated change of the selection in the `ContextWindow` to not to change the selection if the inspections panel accessible.

Context panel - Page tab should remain active after changing page template #296

---

src/main/resources/assets/js/app/content/PageTemplate.ts
src/main/resources/assets/js/app/page/Page.ts
src/main/resources/assets/js/app/page/region/Regions.ts
src/main/resources/assets/js/page-editor/LiveEditModel.ts

-Now switching to template from controller will correctly update Saved button. Issue occurred because of how we treat empty config and regions page objects.

Error appears after changing a template in Inspection Panel #48

---

src/main/resources/assets/js/app/issue/view/IssueDialog.ts
src/main/resources/assets/js/app/publish/ContentPublishDialog.ts
src/main/resources/assets/js/app/publish/PublishProcessor.ts
src/main/resources/i18n/phrases.properties

-PublishProcessor already had 'load started' and 'load finished' listeners, added 'load failed' also
-Handling errors from requests sent to resolve dependencies
-Refactored code

Publish wizard: No error message on resolution failure #70

---

src/main/resources/assets/js/app/wizard/ContentWizardPanel.ts

Updated `ContentWizardPanel.updatePersistedItemIfNeeded()` check for regular content, by changing the `this` value for the `equals()` call, since the `content` may be of type `Site`, while the `current` is always `Content`. Calling the `Site.equals(Content)` will always return `false`, which will cause the update of the wizard.

Page Editor - selection of a component descriptor causes reload of the entire page #367

---

src/main/resources/assets/js/app/wizard/PageComponentsView.ts
src/main/resources/assets/js/page-editor/ItemView.ts
src/main/resources/assets/js/page-editor/ItemViewContextMenu.ts
src/main/resources/assets/js/page-editor/PageView.ts

Updated check for the `ItemView.handleClick` event, to prevent hiding of the context menu due to invalid event calls order.
Refactored event bindings, making it easier to debug.

Page Editor - An extra click is required to unlock the page

---

testing/page_objects/wizardpanel/liveform/page.components.view.js
testing/specs/page-editor/wizard.image.fragment.spec.js

test to verify bug: "Site Wizard Context panel - versions widget closes after rollback a version "

ui-test - issue#417

---

src/main/resources/assets/js/app/wizard/page/LiveFormPanel.ts

Fixed inspection event options, fired after the selection is restored.

Don't open closed Context panel after save #384

---

src/main/resources/assets/js/app/wizard/ContentWizardPanel.ts
src/main/resources/assets/js/app/wizard/page/LiveFormPanel.ts

Added missing arguments to prevent widget change on the model update, just like when changing the version of the page.

 Site Wizard - The Version History widget closes after version rollback #335

---

src/main/resources/assets/js/app/inputtype/ui/text/HtmlEditor.ts

-By default, browser native spell check functionality is disabled in the editor. Enabled it

Browser spellchecker disabled for html-area #391

---

src/main/resources/assets/js/app/inputtype/ui/text/HtmlEditor.ts

-Adding corresponding css styles for each redundant attribute: border -> border, cellspacing -> border-spacing, cellpadding -> padding on td, align -> margin. Done without modifying plugin code.

Table editing in rich text editor uses old legacy format of styling #426

---

src/main/resources/assets/js/app/browse/action/MarkAsReadyContentAction.ts
src/main/resources/assets/js/app/wizard/action/MarkAsReadyAction.ts
src/main/resources/i18n/phrases.properties
src/main/resources/i18n/phrases_ru.properties

Updated browse panel MarkAsReady action, removing confirmation, when single item is selected.

Don't show confirmation when marking a single item is ready #711

---

src/main/resources/assets/js/app/ContentStatusToolbar.ts
src/main/resources/assets/js/app/wizard/ContentWizardPanel.ts
src/main/resources/assets/js/app/wizard/ContentWizardToolbar.ts

Added ignore of the status icon update in case, when content was unnamed, but later was saved with a new name and displayName (server generates two sequential node update events).

"In progress" icon blinks when saving a new content #732

---

src/main/resources/assets/js/app/content/ContentSummaryAndCompareStatusViewer.ts
src/main/resources/assets/js/app/layer/ContentOfLayerViewer.ts
src/main/resources/assets/js/app/view/context/widget/layers/LayersWidgetStateView.ts
src/main/resources/assets/js/app/view/context/widget/layers/LayersWidgetStateViewLocal.ts
src/main/resources/assets/styles/browse/content-tree-grid.less
src/main/resources/assets/styles/content/content-summary-and-compare-status-viewer.less
src/main/resources/assets/styles/main.less
src/main/resources/assets/styles/view/context/widget-layers.less
src/main/resources/assets/styles/view/context/widget-view.less
src/main/resources/i18n/phrases.properties

* Updated layers widget view styling.
* Added content and layer viewer to the head of the local item.
* Replaced `<el>` with `<span>` and `margin` with whitespace in the `::before` to match the current font size and width.

Display layer icon/item details for local items in the Layers widget #772

---

testing/page_objects/browsepanel/content.browse.panel.js
testing/page_objects/components/loader.combobox.js
testing/page_objects/wizardpanel/content.wizard.panel.js
testing/specs/publish/wizard.mark.as.ready.spec.js
testing/specs/publish/wizard.publish.menu.workflow.spec.js

verifies - https://github.com/enonic/app-contentstudio/issues/891 Work In Progress state should not be displayed for Deleted content
verifies https://github.com/enonic/app-contentstudio/issues/692   'Publish...' should be the default action for content in Deleted state

ui-tests issue#891

---

src/main/resources/assets/styles/dialog/dependant-items-dialog.less
src/main/resources/assets/styles/publish/issue-comment-list.less
src/main/resources/assets/styles/publish/issue-details-dialog.less
src/main/resources/assets/styles/publish/issue-dialog.less

* Updated padding in the footer of the IssueDetailsDialog on Assignees tab.
__In addition:__
* Decreased space between comments.
* Removed spacing on the right of the assignees' list, making it similar to the items list.
* Added word breaking, when comments overflow the comments section, e.g. when you comment with long words without the whitespaces (links, etc.).
* Fixed different height of the dialog buttons on each tab.

Issue Details Dialog - increase top padding in the footer #871

---

src/main/resources/assets/js/app/view/ContentItemPreviewToolbar.ts

* Decreased the debounce timeout from 500ms to 100ms. According to the [RAIL](https://developers.google.com/web/fundamentals/performance/rail) model, when the dealy is 100ms or smaller, users feel like the result is immediate.

Publish Request and Issue list is displayed with a noticeable delay #866

---

src/main/resources/assets/js/app/wizard/ContentWizardPanel.ts
src/main/resources/assets/js/app/wizard/ContentWizardToolbar.ts
src/main/resources/assets/js/app/wizard/WorkflowStateIconsManager.ts

* Moved icons status management in wizard and toolbar to a separate manager.
* Added icon state update, when changes were made to the content with "Pending delete", and the "Undo delete" was clicked.

Content Editor - after publishing, status is visually toggled to "in progress" and showing "unpublish" as default action #843

---

src/main/resources/assets/js/app/wizard/page/contextwindow/inspect/page/PageInspectionPanel.ts

Disabled lazy render for the form view in the components widgets, since it may cause the ill-timed call of the render method, which is leading to `onRendered` parent listener not to be called in `FormItemLayer` and children items not added into the `FormView`.

Page template config is not shown in the Inspect panel #947

---

src/main/resources/assets/js/app/application/ApplicationBasedCache.ts
src/main/resources/assets/js/app/resource/GetLayoutDescriptorsByApplicationRequest.ts
src/main/resources/assets/js/app/resource/GetPageDescriptorsByApplicationRequest.ts
src/main/resources/assets/js/app/resource/GetPartDescriptorsByApplicationRequest.ts
src/main/resources/assets/js/app/wizard/page/contextwindow/inspect/page/GetPageDescriptorsByApplicationsRequest.ts
src/main/resources/assets/js/app/wizard/page/contextwindow/inspect/page/PageDescriptorDropdown.ts
src/main/resources/assets/js/app/wizard/page/contextwindow/inspect/region/DescriptorBasedComponentInspectionPanel.ts
src/main/resources/assets/js/app/wizard/page/contextwindow/inspect/region/GetComponentDescriptorsByApplicationsRequest.ts
src/main/resources/assets/js/app/wizard/page/contextwindow/inspect/region/GetLayoutDescriptorsByApplicationsRequest.ts
src/main/resources/assets/js/app/wizard/page/contextwindow/inspect/region/GetPartDescriptorsByApplicationsRequest.ts

- adapted ApplicationBasedCache to work with multiple app keys and cache requests with empty responses as well
- changed GetDescriptorsByApplication*S* requests for Page/Layout/Part to make requests to corresponding endpoints instead of doing multiple GetDescriptorsByApplication requests
- also debounced descriptors reload on applications change that reduced No of requests in case of selecting multiple applications with checkboxes

Fetch component descriptors for all applications with one request #875

---

src/main/resources/assets/js/app/wizard/UpdatePersistedContentRoutine.ts

…he selector. #1024
- fixed a lost promise causing page reload to happen before save has finished

Page controller is not set after selecting it from the selector

---

src/main/resources/assets/js/app/wizard/page/contextwindow/inspect/page/PageInspectionPanel.ts
src/main/resources/assets/js/page-editor/PageModel.ts

NPE was occurring when saving page with template set that refers to controller(descriptor) that has config
-No config will be saved with content's page obj that has template set
-Not rendering template's controller's config in page inspection panel

Can't serialize Page with config and without the descriptor #1062

---

src/main/resources/assets/js/app/inputtype/ui/selector/image/ImageContentComboBox.ts
src/main/resources/assets/js/app/wizard/ContentWizardPanel.ts
src/main/resources/assets/js/app/wizard/page/contextwindow/inspect/region/ImageInspectionPanel.ts

-Issue origin: name/path update of content is not handled, thus dropdowns in inspection panel can't find items by old paths
-Added handling of rename event, triggering update in case name/path of content itself or it's parent changed

Descriptor dropdowns in the Inspection panel is not updated after content path has changed

---

src/main/resources/assets/js/app/issue/view/IssueDetailsDialog.ts
src/main/resources/assets/js/app/issue/view/IssueDetailsDialogSubTitle.ts

-Issue's update is invoked via debounced function, in certain cases like adding assignees even call to a debounced function is async itself; So debounced issue update might be triggered after details dialog is closed and it's fields' values are reset, thus we end up with issue update request set with empty values. Solved by adding a flag that signalizes that update is going to be triggered and then on closing dialog we first invoke update immediately so it is run with actual values

Debounced update results in incorrect layout in the Issue Detail dialog

---

src/main/resources/assets/js/app/wizard/PageComponentsView.ts

-New node representing added component is appearing in PCV only after async 'expandNode' is finished, thus attempt to select this node before it is actually added to the grid fails. Solved by handling selection routine only after async 'expandNode' is finished

New component loses selection if Page Component View was open #1158

---

src/main/resources/assets/js/app/wizard/PageComponentsView.ts

-Setting pageView to PCV triggers PCV grid reload; during grid reload attempt to restore selection fails; Solved by saving selectedItemId and restoring selection in PCV after grid reload

Page Component View loses selection after changes are saved #936

---

src/main/resources/assets/js/app/inputtype/ui/selector/image/ImageContentComboBox.ts
src/main/resources/assets/js/app/wizard/page/contextwindow/inspect/region/ImageInspectionPanel.ts

-Selected option in ImageInspectionPanel was not cleaned before updating it in case when content representing image was not loaded in first batch of data during update, thus it remained selected
-Solved by forcing selection cleanup during update when selected option content not found in dropdown options

Inspect Panel is not correctly rendered after inserting an image. #1176

---

src/main/resources/assets/js/app/inputtype/ui/text/HtmlEditor.ts

-Issue origin: image widget plugin wraps figure element that is centered with alignment
-Solved by overriding required function in image plugin code

Centered images in HTML Area become left-aligned in edit mode #1289

---

src/main/resources/assets/js/app/inputtype/ui/text/HtmlEditor.ts

-cke's image plugin logic doesn't expect figure to be topmost widget element and doesn't set internally alignment to be 'center', thus alignment classes are getting wiped out during init
-Fixed by setting image widget's internal data.align = 'center' for a center image when upcasting figure to an image widget

Issues with mid-aligning images in html-area #1444

---

src/main/resources/assets/js/app/inputtype/text/HtmlArea.ts
src/main/resources/assets/js/app/inputtype/ui/text/HtmlEditor.ts
src/main/resources/assets/js/app/inputtype/ui/text/dialog/FullscreenDialog.ts

-Using editor setData with option 'internal' set to 'true' when updating editor, that suppresses any event fired by cke when copying data internally inside the editor - one of this events was triggering changing scrollTop

Keep cursor position inside HTML editor after content is saved #1426

---

testing/page_objects/wizardpanel/liveform/page.components.view.js
testing/specs/content.xdata.outbound.dependency.spec.js
testing/specs/page-editor/insert.part.htmlarea.spec.js

Verifies https://github.com/enonic/app-contentstudio/issues/1523 
"Custom icon is overwritten with the default icon in Fragment wizard"

ui-tests - issue#1524

---

src/main/resources/assets/js/app/inputtype/text/HtmlArea.ts
src/main/resources/assets/js/app/inputtype/ui/text/HtmlEditor.ts

-Removed usage of 'internal' property in setData, it prevents immediate update of editor content
-Updated setEditorContent() function in HtmlArea: invoking setData only when data changed, thus focus won't be lost after editor's updated on save

Html Area is not updated after reverting a version #1500

---

testing/libs/elements.js
testing/libs/studio.utils.js
testing/page_objects/components/text.component.js
testing/page_objects/wizardpanel/content.wizard.panel.js
testing/specs/page-editor/generate.name.for.fragments.spec.js
testing/specs/page-editor/image.component.inspect.panel.spec.js
testing/specs/wizard.tag.allowpath.spec.js

Verifies
1)  https://github.com/enonic/app-contentstudio/issues/1455 Text component name should be sanitised
2) xp/issues/7831, Component Names - generate proper names for Fragment component #7831

ui-tests for generated names for Fragments issue#1452

---

src/main/resources/assets/js/app/event/ContentServerEventsHandler.ts
src/main/resources/assets/js/app/view/MobileContentItemStatisticsPanel.ts

Unhandled error occurred in MobileContentItemStatisticsPanel, so
1. Fixed error
2. Added catch() clause on event handling promise, thus error is displayed in console

Status is not refreshed in browse panel #1560

---

src/main/resources/assets/js/app/issue/view/IssueDetailsDialog.ts

-Removed switching to comments tab on issue details dialog's setIssue

Task Details Dialog switches to the Comments tab after save #1571

---

src/main/resources/assets/js/app/wizard/PageComponentsTreeGrid.ts

-FragmentComponentView's content is loaded async and is not there yet by the time when Page Components grid is creating its nodes, thus subname is generated without knowing type of fragment's content. Also due to the way how nodes are being generated - by triggering toString on viewer and making new Element from that string - original viewer is not reachable, thus have to invalidate fragment's node to trigger node rerender after fragment's content loaded

Page Component View - incorrect description of a fragment #1534

---

src/main/resources/assets/js/app/inputtype/text/HtmlArea.ts
src/main/resources/assets/js/app/inputtype/ui/text/HtmlEditor.ts

-all update related attributes( like dirty flag, original value etc.) are stored in hidden TextArea element, thus need to duplicate editor's content in TextArea element for updates to be received and handled correctly
-added 'callback' param for editor's setData method to differentiate between user input and update events that must be handled differently

HTML Area fields are cleared on concurrent content update #1692

---

src/main/resources/assets/js/app/inputtype/selector/ImageSelector.ts
src/main/resources/assets/js/app/inputtype/ui/selector/image/ImageContentLoader.ts
src/main/resources/assets/js/app/inputtype/ui/selector/image/ImageOptionDataLoader.ts
src/main/resources/assets/js/app/inputtype/ui/selector/image/ImageSelectorSelectedOptionView.ts
src/main/resources/assets/js/app/inputtype/ui/selector/image/ImageSelectorSelectedOptionsView.ts
src/main/resources/assets/js/app/inputtype/ui/selector/image/ImageSelectorViewer.ts
src/main/resources/assets/js/app/inputtype/ui/selector/media/MediaSelectorDisplayValue.ts
src/main/resources/assets/js/app/inputtype/ui/selector/media/MediaTreeSelectorItem.ts
src/main/resources/assets/styles/inputtype/selector/image-selector.less
src/main/resources/i18n/phrases.properties

-First problem solved: ImageContentLoader was NOT RESOLVING promises for content ids that were not found (deleted), thus .then block for missing ids was never invoked (now returning null for that case when resolving)
-Second promblem solved: Deleted images remain in content's data, thus in content wizard these values were not shown as selected but silently influence on viewed and persisted content comparison. Now showing missing selected ImageSelector items so user could see what and where is missing and manually delete them.
There's second option available for missing images, same as for ContentSelector - delete missing images ids from data after opening wizard and notifying user that reference to be removed on save.

Image Selector with deleted image is not properly validated #1479

---

src/main/resources/assets/js/app/wizard/page/IEObjectHolder.ts
src/main/resources/assets/js/app/wizard/page/IEObjectProcessor.ts
src/main/resources/assets/js/app/wizard/page/LiveEditPageProxy.ts

-Updated processing of stored before load objects for IE: now saving components' names because they are not saved in toJSON serialization and will be set back when objects restored

[IE 11] Error when opening a site in Page Editor #1484

---

src/main/resources/assets/js/app/inputtype/ui/selector/image/ImageEditor.ts

-focus and crop data must have auto value set to 'true' by default; Error occurred on image update when values were not set correctly due to 'auto' prop in crop and focus data being 'null'

Console errors when uploading an image inside the Image Editor #1971

---

src/main/resources/assets/js/app/content/ContentSummaryAndCompareStatusViewer.ts

The new logic is as follows:
1) If current project/layer does **not** have a default language set, we assume that language is not used/not important for this project/layer. In this case no language will be displayed in the Grid for the content item (no matter if it has the language or not).
2) If default project is **set** for the current project/layer and the item's language is **not set**, "(?)" will be displayed after display name
3) If default project is **set** for the current project/layer and the item's language is different, then the item's language will be shown in brackets to visualise that the item's language is different from the default language of the project/layer.
4) If the item's language is the same as default language of the current project/layer, no language will be …

Visualize missing language in the Content grid

---

src/main/resources/assets/js/app/ContentAppPanel.ts
src/main/resources/assets/js/app/ContentEventsProcessor.ts
src/main/resources/assets/js/app/UrlAction.ts
src/main/resources/assets/js/app/wizard/ContentAppHelper.ts
src/main/resources/assets/js/app/wizard/ContentWizardPanel.ts
src/main/resources/assets/js/app/wizard/ContentWizardPanelParams.ts

-Added 'localize' url action
-When opening inherited item in current layer from browse panel url will be constructed with 'localize'
-Layer language for inherited item in wizard panel will only be set only if 'localize' presents in url
-'localize' in url will be replaced with 'edit' after item is saved or if item is initially not inherited

Localisation should work only in the current layer #2298

---

src/main/resources/assets/js/app/wizard/ContentWizardHeader.ts

-AutosizeTextInput won't update it's size if it is invisible, so need first make it visible on renaming and then set it's new name

Path for Moved content should not be truncated in wizard #2434

---

src/main/resources/assets/js/app/wizard/PageComponentsGridDragHandler.ts
src/main/resources/assets/js/app/wizard/PageComponentsTreeGrid.ts
src/main/resources/assets/js/app/wizard/PageComponentsView.ts
src/main/resources/assets/js/page-editor/ComponentView.ts
src/main/resources/assets/js/page-editor/ItemView.ts
src/main/resources/assets/js/page-editor/ItemViewTreeGridWrapper.ts

-Issue was with item ids, we have to separate ItemView html element id and ItemView's data id. Because of thius we're not really supposed to use ItemView as a TreeGrid data object, thus using wrapper for ItemView in treegrid so we could distinguish between data and element id

Incorrect ID of inserted page editor item #2465
