src/main/resources/assets/js/app/inputtype/ui/text/dialog/image/ImageModalDialog.ts

-Suppresing cke native image dialog's change event on image element that alters url

CKE alters image URL after inserting an image with custom style #65

---

testing/libs/elements.js
testing/page_objects/browsepanel/detailspanel/user.access.widget.itemview.js
testing/page_objects/wizardpanel/liveform/inspection/image.inspection.panel.js
testing/page_objects/wizardpanel/liveform/page.components.view.js
testing/specs/edit.permissions.dialog.accessselector.spec.js
testing/specs/edit.permissions.dialog.spec.js
testing/specs/overwrite.permissions.spec.js
testing/specs/page-editor/image.component.inspect.panel.spec.js
testing/specs/wizard.update.permissions.spec.js

ui-test to verify 'app-contentstudio#77'

ui-tests for caption in Inspect Panel

---

src/main/resources/assets/js/app/browse/ContentPublishMenuButton.ts
src/main/resources/assets/js/app/wizard/ContentWizardPanel.ts
src/main/resources/assets/js/app/wizard/ContentWizardToolbarPublishControls.ts

-brought back mistakenly removed create issue action listener
-checking user publish permissions when permissions updated

Publish menu button - incorrect behaviour in the Wizard #173

---

src/main/resources/assets/js/app/wizard/ContentWizardPanel.ts
src/main/resources/assets/page-editor/styles/partials/page-view.less
src/main/resources/assets/styles/view/context/context-panel.less
src/main/resources/assets/styles/view/mobile-content-item-statistics-panel.less
src/main/resources/assets/styles/wizard/content-wizard-panel.less

* Disabled automatic maximization of the wizard, when a component was clicked to be inspected.
* Updated transparency in the mobile mode of context panel.
* Fixed the position of the context panel toggle button in mobile mode, when page editor is visible.
* Fixed the z-index of the template icon in the empty page editor

Incorrect wizard panel minimization behavior #192 

---

package-lock.json
package.json
src/main/resources/assets/js/app/wizard/page/contextwindow/inspect/BaseInspectionPanel.ts
src/main/resources/assets/lib/index.js
src/main/resources/assets/lib/jquery.slimscroll.d.ts

Updated scroll size from 7px to 10px.

Increase scrollbar width inside the Inspect panel #123

---

src/main/resources/assets/js/page-editor/fragment/FragmentComponentView.ts

Updated html area image converter to use actual content id.

Error message appears after saving a fragment #183

---

src/main/resources/assets/js/app/view/context/ContextSplitPanel.ts
src/main/resources/assets/js/app/view/context/ContextView.ts
src/main/resources/assets/js/app/wizard/ContentWizardPanel.ts
src/main/resources/assets/js/app/wizard/page/LiveFormPanel.ts
src/main/resources/assets/styles/view/context/context-panel.less
src/main/resources/assets/styles/wizard/content-wizard-panel.less

* Updated widgets selector to be above the load mask.
* Load mask position is adjusted in the previous fixes to Context panel.
* Multiple spinners are no longer appears.

Spinner appears several times on the Details Panel #133

---

src/main/resources/assets/js/app/dialog/DependantItemsDialog.ts
src/main/resources/assets/js/app/duplicate/ContentDuplicateDialog.ts
src/main/resources/assets/js/app/issue/view/IssueDetailsDialog.ts
src/main/resources/assets/js/app/issue/view/IssueDialog.ts
src/main/resources/assets/js/app/publish/ContentPublishDialog.ts
src/main/resources/assets/js/app/remove/ContentDeleteDialog.ts

-Default values of instance variables were set after initElements invoked; Need to init instance vars in init elements

Publishing Wizard - dependent items should be hidden by default #208

---

src/main/resources/assets/js/app/browse/ContentBrowsePanel.ts
src/main/resources/assets/js/app/browse/ContentBrowsePublishMenuButton.ts
src/main/resources/assets/js/app/browse/ContentPublishMenuButton.ts
src/main/resources/assets/js/app/wizard/ContentWizardToolbarPublishControls.ts

-Moved PublishTree action to a child ContentPublishMenuButton class that is used by browse panel

"Publish Tree" action should be removed from the Wizard #235

---

src/main/resources/assets/js/app/page/PageMode.ts
src/main/resources/assets/js/app/wizard/ContentWizardPanel.ts
src/main/resources/assets/js/app/wizard/page/LiveFormPanel.ts
src/main/resources/assets/js/app/wizard/page/contextwindow/ContextWindow.ts
src/main/resources/assets/styles/wizard/page/contextwindow/context-window.less

* Updated page inspection panel to be hidden for fragment wizard.
* Removed obsolete code.

Fragment wizard - Incorrect tab is displayed in the context panel #216

---

src/main/resources/assets/js/app/inputtype/ui/text/HtmlEditor.ts
src/main/resources/assets/lib/ckeditor/plugins/pasteFromGoogleDoc/plugin.js

-Using plugin https://ckeditor.com/cke4/addon/pasteFromGoogleDoc

Pasting from Word into Enonic doesn't remove formatting #255

---

src/main/resources/assets/js/app/wizard/page/contextwindow/inspect/page/PageTemplateAndControllerSelector.ts
src/main/resources/assets/js/page-editor/PageView.ts

Added change of the lock status, when selecting template.

Page is not blocked after switching from controller to template #280

---

src/main/resources/assets/js/app/inputtype/ui/text/dialog/image/ImageModalDialog.ts
src/main/resources/assets/js/app/page/region/ImageComponent.ts
src/main/resources/assets/js/app/util/ImageHelper.ts
src/main/resources/assets/js/app/wizard/page/contextwindow/inspect/region/ImageInspectionPanel.ts
src/main/resources/assets/js/page-editor/image/ImagePlaceholder.ts

-Have to fetch full image content out of ImageComponent class, otherwise circular dependency occurs during build

Set default value for the "Caption" field in ImageInspectionPanel #304

---

src/main/resources/assets/js/app/inputtype/text/HtmlArea.ts

-removed some redundant code related to input height, and that helped

Html Area content - broken layout after version rollback #34

---

src/main/resources/assets/js/app/event/InspectEvent.ts
src/main/resources/assets/js/app/view/context/ContextView.ts
src/main/resources/assets/js/app/wizard/ContentWizardPanel.ts
src/main/resources/assets/js/app/wizard/PageComponentsView.ts
src/main/resources/assets/js/app/wizard/page/LiveFormPanel.ts
src/main/resources/assets/js/app/wizard/page/contextwindow/ContextWindow.ts
src/main/resources/assets/js/page-editor/ComponentView.ts
src/main/resources/assets/js/page-editor/ItemView.ts
src/main/resources/assets/js/page-editor/ItemViewAddedEvent.ts
src/main/resources/assets/js/page-editor/ItemViewSelectedEvent.ts
src/main/resources/assets/js/page-editor/PageView.ts
src/main/resources/assets/js/page-editor/RegionView.ts
src/main/resources/assets/js/page-editor/layout/LayoutComponentView.ts

* Prevented widget change, when selection is restored.
* Refactored component view selection.

Site Wizard Context panel - versions widget closes after rollback a version #335

---

src/main/resources/i18n/phrases_pl.properties

New translations to Polish for the new XP, version 7.0.0

#311 Translate new phrases to Polish

---

src/main/resources/assets/js/app/create/NewContentDialog.ts
src/main/resources/assets/js/app/dialog/DependantItemsDialog.ts
src/main/resources/assets/js/app/duplicate/ContentDuplicateDialog.ts
src/main/resources/assets/js/app/issue/view/IssueDetailsDialog.ts
src/main/resources/assets/js/app/issue/view/IssueDialog.ts
src/main/resources/assets/js/app/issue/view/IssueListDialog.ts
src/main/resources/assets/js/app/publish/ContentPublishDialog.ts
src/main/resources/assets/js/app/publish/ContentUnpublishDialog.ts
src/main/resources/assets/js/app/remove/ContentDeleteDialog.ts
src/main/resources/assets/styles/publish/issue-dialog.less

-Moving load mask show/hide related code out of dialogs to their common parent
-Showing modal dialog only when dialog is rendered and shown, otherwise waiting for dialog to be shown

Endless spinner after clicking on Create Issue button #356

---

src/main/resources/i18n/phrases_sv.properties

This should be the last three phrases you mentioned in last message. The message before that stated even more phrases missing, but I see those in this file.

Add three missing phrases

---

src/main/resources/assets/js/app/wizard/page/LiveFormPanel.ts
src/main/resources/assets/js/page-editor/ItemViewSelectedEvent.ts
src/main/resources/assets/js/page-editor/PageSelectedEvent.ts
src/main/resources/assets/js/page-editor/PageView.ts
src/main/resources/assets/js/page-editor/RegionSelectedEvent.ts
src/main/resources/assets/js/page-editor/RegionView.ts
src/main/resources/assets/js/page-editor/SelectedByClickEvent.ts

Removed inspection event, if the item view was right-clicked.

Don't open Context panel on a right-click in the Page Editor #380

---

src/main/resources/assets/js/app/wizard/ContentWizardPanel.ts

-Fixed syncing persisted content data with data we get in wizard after wizard layout or update (adding missing properties to persisted data from COPIED viewed data, not original viewed properties). Also cleaning copied viewed data option sets from non selected properties that are not saved (before adding missing data to persisted item data)

OptionSet wizard - Incorrect behavior of validation #400

---

src/main/resources/assets/js/app/view/context/ActiveContextPanelManager.ts
src/main/resources/assets/js/app/view/context/SlidablePanel.ts
src/main/resources/assets/styles/view/context/context-panel.less
src/main/resources/assets/styles/wizard/page/live-form-panel.less

Updated splitter for the floating panel to be visible and draggable.

Enable expanding Context panel in floating mode

---

src/main/resources/assets/js/app/inputtype/customselector/CustomSelector.ts
src/main/resources/assets/js/app/inputtype/customselector/CustomSelectorComboBox.ts

Added missing sorting setup in the CustomSelector.

Drag'n'Drop of selected options in Custom selector is not working #440

---

src/main/resources/assets/js/app/publish/PublishDialogDependantList.ts
src/main/resources/assets/js/app/publish/PublishProcessor.ts

-Dependant item becomes removable after it's dependant items removed from list, just need to update view to correspond

UI problem removing dependencies #484

---

src/main/resources/assets/js/app/inputtype/ui/text/HTMLAreaHelper.ts

-Fixed converting image's src 'image://' to real one, problem was with handling regexp

Browser freezes when trying to process video tag inside HTML Area #504

---

testing/libs/studio.utils.js
testing/page_objects/browsepanel/content.browse.panel.js
testing/page_objects/wizardpanel/content.wizard.panel.js
testing/specs/publish/publish.dialog.site.with.children.spec.js
testing/specs/publish/toolbar.publish.menu.site.spec.js

Tests to verify issue : 'Create Issue' button appears on the toolbar after publishing site's child items
#493

ui-tests -  issue#503

---

src/main/resources/assets/js/app/browse/ContentBrowsePanel.ts
src/main/resources/assets/js/app/browse/ContentTreeGrid.ts
src/main/resources/assets/js/app/browse/TreeNodesOfContentPath.ts
src/main/resources/assets/js/app/resource/ContentSummaryAndCompareStatusFetcher.ts

-Broke all extra large functions into smaller ones
-Removed redundant code wherever possible

Refactor ContentTreeGrid #1007

---

src/main/resources/assets/js/app/browse/SortContentDialog.ts
src/main/resources/assets/js/app/browse/SortContentTreeGrid.ts
src/main/resources/assets/js/page-editor/ItemView.ts
src/main/resources/assets/styles/browse/sort-content-dialog.less

-Upgrading deprecated jquery function

Upgrade jQuery to 3.4.1

---

src/main/resources/assets/js/app/browse/ContentBrowsePanel.ts
src/main/resources/assets/js/app/browse/ContentBrowsePublishMenuButton.ts
src/main/resources/assets/js/app/browse/ContentPublishMenuButton.ts
src/main/resources/assets/js/app/browse/action/ContentTreeGridActions.ts
src/main/resources/assets/js/app/browse/action/MarkAsReadyContentAction.ts
src/main/resources/assets/js/app/content/ContentSummaryAndCompareStatusViewer.ts
src/main/resources/assets/js/app/publish/PublishDialogDependantList.ts
src/main/resources/assets/js/app/publish/PublishProcessor.ts
src/main/resources/assets/js/app/resource/MarkAsReadyRequest.ts
src/main/resources/assets/js/app/resource/UpdateContentRequest.ts
src/main/resources/assets/js/app/wizard/ContentWizardPanel.ts
src/main/resources/assets/js/app/wizard/ContentWizardToolbar.ts
src/main/resources/assets/js/app/wizard/ContentWizardToolbarPublishControls.ts
src/main/resources/assets/js/app/wizard/action/ContentWizardActions.ts
src/main/resources/assets/js/app/wizard/action/MarkAsReadyAction.ts
src/main/resources/assets/styles/browse/content-publish-menu-button.less
src/main/resources/i18n/phrases.properties
src/main/resources/i18n/phrases_ru.properties

Requires:
1. https://github.com/enonic/xp/pull/7209
2. https://github.com/enonic/lib-admin-ui/pull/1033

Implement "Mark as Ready" action #515

---

src/main/resources/assets/js/app/inputtype/ui/selector/RowSelector.ts
src/main/resources/assets/js/app/issue/view/IssueListDialog.ts
src/main/resources/assets/js/app/issue/view/IssuesPanel.ts
src/main/resources/assets/styles/inputtype/selector/row-selector.less
src/main/resources/assets/styles/main.less
src/main/resources/assets/styles/publish/issue-list-dialog.less
src/main/resources/i18n/phrases.properties
src/main/resources/i18n/phrases_ru.properties

Combined checkboxes filters with filter dropdown.

Implement filter for the Issue List dialog #558

---

src/main/resources/assets/js/app/issue/view/IssueList.ts
src/main/resources/assets/styles/publish/issue-list-dialog.less

* Added status data to the issues list item.
* Disabled assignees data to the issues list item.
_Depends on PR #620_

Show issue status in the issue list #561

---

src/main/resources/assets/icons/icons.less
src/main/resources/assets/js/app/browse/ContentBrowsePublishMenuButton.ts
src/main/resources/assets/js/app/browse/ContentPublishMenuButton.ts
src/main/resources/assets/js/app/wizard/ContentWizardPanel.ts
src/main/resources/assets/js/app/wizard/ContentWizardToolbar.ts
src/main/resources/assets/js/app/wizard/action/BasePublishAction.ts
src/main/resources/assets/js/app/wizard/action/PublishAction.ts
src/main/resources/assets/styles/wizard/thumbnail-uploader-el.less

1. Showing state icon on a thumbnail icon in wizard again
2. Made 'Mark as Ready' default action on a toolbar publish controls if it is enabled
3. Made saving content with status 'Ready' in wizard when opening publish dialog with 'Publish' action in case when content's state is 'In Progress'

Various fixes/updates in content state workflow

---

src/main/resources/assets/js/app/wizard/ContentWizardPanel.ts
src/main/resources/assets/js/app/wizard/page/LiveFormPanel.ts
src/main/resources/assets/js/app/wizard/page/contextwindow/ContextWindow.ts

Prevented model update to call additional inspection event, if the model wasn't changed.

Content Wizard form collapses after publish #547

---

src/main/resources/assets/js/app/browse/ContentTreeGrid.ts

-Making renamed content to be placed in grid correctly (my latest refactoring broke it)

Incorrect sorting in root directory #597

---

src/main/resources/assets/js/app/inputtype/ui/selector/RowSelector.ts
src/main/resources/assets/js/app/issue/IssueSummary.ts
src/main/resources/assets/js/app/issue/IssueType.ts
src/main/resources/assets/js/app/issue/json/IssueSummaryJson.ts
src/main/resources/assets/js/app/issue/resource/GetIssueStatsRequest.ts
src/main/resources/assets/js/app/issue/view/IssueList.ts
src/main/resources/assets/js/app/issue/view/IssueListDialog.ts
src/main/resources/assets/js/app/issue/view/IssuesPanel.ts
src/main/resources/assets/js/app/issue/view/IssuesStorage.ts
src/main/resources/assets/styles/inputtype/selector/row-selector.less
src/main/resources/assets/styles/publish/issue-list-dialog.less

_Depends on [PR to xp](https://github.com/enonic/xp/pull/7238)._

Show Publish Requests on a separate tab in the Issue List dialog #563

---

src/main/resources/assets/icons/publish-request-closed.svg
src/main/resources/assets/icons/publish-request-open.svg
src/main/resources/assets/js/app/inputtype/ui/selector/RowSelector.ts
src/main/resources/assets/js/app/issue/IssueSummary.ts
src/main/resources/assets/js/app/issue/IssueType.ts
src/main/resources/assets/js/app/issue/json/IssueSummaryJson.ts
src/main/resources/assets/js/app/issue/resource/GetIssueStatsRequest.ts
src/main/resources/assets/js/app/issue/view/IssueList.ts
src/main/resources/assets/js/app/issue/view/IssueListDialog.ts
src/main/resources/assets/js/app/issue/view/IssuesPanel.ts
src/main/resources/assets/js/app/issue/view/IssuesStorage.ts
src/main/resources/assets/styles/inputtype/selector/row-selector.less
src/main/resources/assets/styles/publish/issue-list-dialog.less

Change icon for Publish Requests #582

---

src/main/resources/assets/js/app/inputtype/ui/text/dialog/image/ImageModalDialog.ts

-Async methods were triggered before required elements initialized; Moved initialization to initElements as supposed to

MS Edge browser - Insert image dialog does not load correctly #627

---

src/main/resources/assets/js/app/content/ContentLayer.ts
src/main/resources/assets/js/app/layer/LayerViewer.ts
src/main/resources/assets/js/app/layer/LayersList.ts
src/main/resources/assets/js/app/layer/LayersListDialog.ts
src/main/resources/assets/js/app/remove/ConfirmDeleteDialog.ts
src/main/resources/assets/js/app/remove/ContentDeleteDialog.ts
src/main/resources/assets/js/app/resource/layer/DeleteContentLayerRequest.ts
src/main/resources/assets/js/app/view/context/widget/layers/LayersWidgetStateViewMultiLayers.ts
src/main/resources/assets/js/app/view/context/widget/layers/LayersWidgetStateViewNoLayers.ts
src/main/resources/assets/styles/layer/layer-dialog.less
src/main/resources/assets/styles/main.less
src/main/resources/assets/styles/view/context/widget-view.less
src/main/resources/i18n/phrases.properties

NB: Added test data for dialog list for presentation purposes, this list to be removed after 'Create' dialog implemented

Implement Layers List modal dialog #668

---

src/main/resources/assets/js/app/layer/CreateLayerDialog.ts
src/main/resources/assets/js/app/layer/LayerComboBox.ts
src/main/resources/assets/js/app/layer/LayerCreateUpdateDialog.ts
src/main/resources/assets/js/app/layer/LayerDetailsDialog.ts
src/main/resources/assets/js/app/layer/LayerDialogForm.ts
src/main/resources/assets/js/app/layer/LayerViewer.ts
src/main/resources/assets/js/app/layer/LayersListDialog.ts
src/main/resources/assets/js/app/resource/layer/CreateContentLayerRequest.ts
src/main/resources/assets/js/app/resource/layer/UpdateContentLayerRequest.ts
src/main/resources/assets/js/app/view/context/widget/layers/LayersWidgetItemView.ts
src/main/resources/assets/js/app/view/context/widget/layers/LayersWidgetStateViewMultiLayers.ts
src/main/resources/assets/js/app/view/context/widget/layers/LayersWidgetStateViewNoLayers.ts
src/main/resources/assets/styles/layer/layer-dialog.less
src/main/resources/i18n/phrases.properties

Implement New Layer modal dialog #669

---

src/main/resources/assets/js/app/browse/ContentPublishPromptEvent.ts
src/main/resources/assets/js/app/issue/IssueDialogsManager.ts
src/main/resources/assets/js/app/issue/view/IssueDetailsDialog.ts
src/main/resources/assets/js/app/publish/ContentPublishDialog.ts
src/main/resources/assets/js/main.ts
src/main/resources/assets/styles/publish/issue-details-dialog.less

* Updated ContentPublishDialog to a singleton.
* Added ContentPublishDialog to be called from the IssueDetailsDialog.
* Fixed publish list overflow in the details dialog.

Open Publishing Wizard from the Issue dialog #587

---

src/main/resources/assets/js/app/browse/ContentPublishPromptEvent.ts
src/main/resources/assets/js/app/browse/action/PublishContentAction.ts
src/main/resources/assets/js/app/issue/IssueDialogsManager.ts
src/main/resources/assets/js/app/issue/view/IssueDetailsDialog.ts
src/main/resources/assets/js/app/publish/ContentPublishDialog.ts
src/main/resources/assets/js/app/publish/RequestContentPublishDialog.ts
src/main/resources/assets/js/app/wizard/action/PublishAction.ts
src/main/resources/assets/js/app/wizard/action/PublishTreeAction.ts
src/main/resources/assets/js/main.ts
src/main/resources/assets/styles/publish/issue-details-dialog.less

* Added issue title as publish request message.
_Based on PR #695_

Pass publish message and schedule when publishing from a Publish Request #588

---

testing/libs/app_const.js
testing/libs/studio.utils.js
testing/page_objects/browsepanel/content.browse.panel.js
testing/page_objects/components/datetime.range.js
testing/page_objects/confirm.content.delete.dialog.js
testing/page_objects/content.publish.dialog.js
testing/page_objects/request.content.publish.dialog.js
testing/page_objects/wizardpanel/content.wizard.panel.js
testing/page_objects/wizardpanel/details/wizard.versions.widget.js
testing/page_objects/wizardpanel/schedule.wizard.step.form.js
testing/specs/content-types/custom.selector0_2.spec.js
testing/specs/content-types/freeform.nested.set.spec.js
testing/specs/content-types/shortcut.parameters.spec.js
testing/specs/content.workflow.state.spec.js
testing/specs/content.xdata.textarea.spec.js
testing/specs/edit.permissions.dialog.accessselector.spec.js
testing/specs/image.wizard.photo.properties.spec.js
testing/specs/insert.image.dlg.custom.width.spec.js
testing/specs/outbound.dependency.rollback.version.spec.js
testing/specs/page-editor/wizard.image.fragment.spec.js
testing/specs/publish/publish.dialog.site.with.children.spec.js
testing/specs/publish/refresh.publish.content.dialog.spec.js
testing/specs/publish/wizard.publish.menu.workflow.spec.js
testing/specs/publish/wizard.schedule.spec.js
testing/specs/site.wizard.confirm.delete.spec.js
testing/specs/wizard.toolbar.shortcut.spec.js
testing/specs/wizard.update.permissions.spec.js

1. Content in the Publishing Wizard is not updated after it has been changed on the server
#697
2.  https://github.com/enonic/app-contentstudio/issues/709

ui-tests - issue#712

---

src/main/resources/assets/js/app/content/ContentSummaryAndCompareStatusViewer.ts
src/main/resources/assets/js/app/view/context/widget/details/ContentWidgetItemView.ts
src/main/resources/assets/styles/view/context/widget-details.less

* Updated viewer in the details widget panel to show status icon.
* Fixed details widget panel blocks styling, height, and alignment.

Workflow state icons are not shown in the Details widget #719

---

testing/page_objects/browsepanel/contentItem.preview.panel.js
testing/specs/issue/contentitem.preview.toolbar.spec.js

Add ui-test to verify app-contentstudio#721

ui-tests - issue#727

---

src/main/resources/assets/styles/publish/issue-dialog.less

* Updated issue dialog footer styling to prevent visual overlapping of the elements.

Create Issue dialog - hide a vertical scroll bar when not needed #718

---

src/main/resources/assets/js/app/browse/action/ContentTreeGridActions.ts
src/main/resources/assets/js/app/wizard/ContentWizardToolbarPublishControls.ts
src/main/resources/assets/js/app/wizard/action/PublishAction.ts
src/main/resources/assets/js/app/wizard/action/RequestPublishAction.ts

* Updated browse Request Publish action to be enabled when selected content is in progress.
* Updated wizard Request Publish action to be enabled when content is in progress.
* Added content save when publish is requested.

Allow "Request Publishing..." action for items in progress #713 

---

src/main/resources/assets/js/app/issue/view/IssuesPanel.ts
src/main/resources/assets/styles/publish/issue-list-dialog.less
src/main/resources/assets/styles/publish/issues-panel.less

* Updated `IssuesPanel` by hiding the filter, when there is nothing to filter.
* Removed the logic for `OnOffButton` enabling.

Cannot hide closed issues when there are no active ones #756 

---

src/main/resources/assets/js/app/layer/LayerDetailsDialog.ts
src/main/resources/assets/js/app/layer/LayerDialogForm.ts
src/main/resources/assets/js/app/layer/LayerIcon.ts
src/main/resources/assets/js/app/layer/LayerIconUploader.ts
src/main/resources/assets/js/app/layer/LayerViewer.ts
src/main/resources/assets/styles/layer/layer-dialog.less
src/main/resources/assets/styles/layer/layer-icon-uploader.less
src/main/resources/assets/styles/layer/layer-icon.less
src/main/resources/assets/styles/layer/layer-selector.less
src/main/resources/assets/styles/layer/layer-viewer.less
src/main/resources/assets/styles/main.less

Added layout icon with flag to the layer dialogs.
Added icon with flag to the layer viewer.

Fixes for the icon selector in the layer dialog #768

---

src/main/resources/assets/styles/inputtype/text/htmlarea/modal-dialog.less

Broken layout in modal dailogs #765

---

src/main/resources/assets/js/app/dialog/BasePublishDialog.ts
src/main/resources/assets/js/app/issue/view/IssueDetailsDialog.ts
src/main/resources/assets/js/app/publish/RequestContentPublishDialog.ts
src/main/resources/assets/styles/publish/issue-details-dialog.less

Request Content Publish Dialog - Create request button should be disabled when required input is empty #867

Issue Details Dialog - dialog's tabs are not correctly rendered #860

---

src/main/resources/assets/js/app/content/ContentSummaryAndCompareStatusViewer.ts
src/main/resources/assets/js/app/publish/PublishDialogDependantList.ts
src/main/resources/assets/js/app/wizard/ContentWizardPanel.ts
src/main/resources/assets/js/app/wizard/ContentWizardToolbar.ts

-Only invalid will be shown for deleted item

Workflow state should not be displayed for Deleted content #891

---

testing/specs/publish/browse.panel.mark.as.ready.single.content.spec.js

Single item should be automatically marked as ready when Publish or Request Publish dialogs are opened #892

ui-tests issue#932

---

testing/page_objects/components/datetime.range.js
testing/page_objects/content.publish.dialog.js
testing/specs/publish/refresh.publish.content.dialog.spec.js

Test to verify "Publishing Wizard- arrows are closing date time picker"

ui-test - issue#948

---

testing/libs/app_const.js
testing/libs/elements.js
testing/libs/studio.utils.js
testing/page_objects/wizardpanel/content.wizard.panel.js
testing/page_objects/wizardpanel/details/wizard.details.panel.js
testing/page_objects/wizardpanel/imageselector.form.panel.js
testing/specs/page-editor/template.config.spec.js
testing/specs/site.controller.spec.js
testing/specs/wizard.detailspanel.update.dependencies.spec.js

Add ui-test to verify app-contentstudio#969

ui-test - issue#973

---

testing/page_objects/issue/issue.details.items.tab.js
testing/page_objects/issue/issue.list.dialog.js
testing/page_objects/wizardpanel/content.wizard.panel.js
testing/specs/issue/issue.not.valid.content.spec.js
testing/specs/issue/publish.request.dialog.add.items.spec.js
testing/specs/issue/wizard.publish.menu.issue.item.spec.js

test that verifies : Wizard - Publish Menu is not updated after item is removed from an issue or request. #808

ui-tests - issue#809

---

testing/page_objects/browsepanel/content.browse.panel.js
testing/page_objects/content.duplicate.dialog.js
testing/page_objects/page.js
testing/page_objects/wizardpanel/liveform/page.components.view.js
testing/specs/content.duplicate.dialog.spec.js
testing/specs/content.duplicate.spec.js
testing/specs/image.wizard.photo.properties.spec.js
testing/specs/publish/publish.tree.check.child.spec.js

Verifies - Publish Tree action - implement a check for unpublished child items #174

ui-tests issue#189

---

testing/libs/studio.utils.js
testing/package.json
testing/page_objects/wizardpanel/htmlarea.form.panel.js
testing/page_objects/wizardpanel/imageselector.form.panel.js
testing/specs/content-types/htmlarea.cke.toolbar.spec.js
testing/specs/content.duplicate.spec.js
testing/specs/content.image.selector.spec.js
testing/specs/publish/publish.tree.check.child.spec.js
testing/specs/wizard.save.button.spec.js

Duplicate dialog - Duplicate button does not contain a number of content to duplicate, when content are selected by clicking on checkboxes #1015

ui-tests issue#1016

---

testing/page_objects/wizardpanel/liveform/live.form.panel.js
testing/specs/content.duplicate.spec.js
testing/specs/page-editor/page.template.controller.spec.js
testing/specs/page-editor/site.with.several.templates.spec.js
testing/specs/page-editor/site.with.template.spec.js
testing/specs/page-editor/text.component.anchor.spec.js
testing/specs/page-editor/wizard.image.fragment.spec.js

Add ui-test for checking of workflow state of a duplicated content  + code clean up

ui-test - workflow state of duplicated content issue#1002

---

src/main/resources/assets/js/app/wizard/ContentWizardPanel.ts
src/main/resources/assets/js/app/wizard/page/LiveFormPanel.ts
src/main/resources/assets/js/app/wizard/page/contextwindow/inspect/page/PageInspectionPanel.ts
src/main/resources/assets/js/app/wizard/page/contextwindow/inspect/region/DescriptorBasedComponentInspectionPanel.ts
src/main/resources/assets/js/app/wizard/page/contextwindow/inspect/region/FragmentInspectionPanel.ts

Page template config is not shown in the Inspect panel #947

---

testing/page_objects/browsepanel/content.browse.panel.js
testing/specs/content.duplicate.spec.js

ui-tests issue#1053

---

src/main/resources/assets/js/app/inputtype/text/HtmlArea.ts
src/main/resources/assets/js/app/inputtype/ui/text/HtmlEditor.ts
src/main/resources/assets/js/app/inputtype/ui/text/dialog/FullscreenDialog.ts
src/main/resources/assets/styles/inputtype/text/htmlarea/fullscreen-dialog.less
src/main/resources/assets/styles/inputtype/text/htmlarea/html-editor.less

Requires  https://github.com/enonic/lib-admin-ui/pull/1116

Improve Fullscreen mode in HTML Editor #1074

---

testing/page_objects/browsepanel/content.browse.panel.js
testing/page_objects/components/loader.combobox.js
testing/page_objects/content.publish.dialog.js
testing/page_objects/wizardpanel/content.wizard.panel.js
testing/page_objects/wizardpanel/liveform/live.form.panel.js
testing/page_objects/wizardpanel/liveform/page.components.view.js
testing/specs/page-editor/fragment.move.spec.js
testing/specs/page-editor/insert.part.htmlarea.spec.js
testing/specs/page-editor/text.component.cke.url.link.spec.js
testing/specs/publish/publish.modified.deleted.content.spec.js

test to verify issue:   Page Editor is not updated after content is saved #1096

ui-tests issue#1098 + fix for failed tests

---

src/main/resources/assets/js/app/browse/action/ContentTreeGridActions.ts
src/main/resources/assets/js/app/browse/action/MarkAsReadyContentAction.ts
src/main/resources/assets/js/app/content/ContentSummaryAndCompareStatus.ts

-Added check for pending delete status

Mark As Ready should not be enabled for deleted content #1083

---

src/main/resources/assets/js/app/issue/view/IssueList.ts
src/main/resources/assets/js/app/issue/view/IssueListDialog.ts
src/main/resources/assets/js/app/issue/view/IssuesPanel.ts
src/main/resources/assets/styles/publish/issue-list-dialog.less

-Added 'Tab' navigation that goes through issues list items and then switches to a next tab

Incorrect behaviour of tab navigation inside the Issue List dialog

---

src/main/resources/assets/js/app/wizard/ContentWizardPanel.ts

…ab if wizard for this item is already opened #822

Don't open a new browser tab for a clicked item in the modal dialog if the Wizard is already opened 

---

src/main/resources/assets/js/app/inputtype/ui/selector/image/ImageSelectorSelectedOptionsView.ts

…res exceeds the required value #969
-Max Occurrences were not checked before adding selected option in image selected options view

Incorrect validation in Image Selector when the number of selected images exceeds allowed value

---

src/main/resources/assets/js/app/wizard/ContentWizardToolbar.ts
src/main/resources/i18n/phrases.properties

-Added missing phrase
-Updating title on toggled

Page Editor - tooltip 'Hide Component View' does not appear. #1108

---

testing/page_objects/wizardpanel/content.wizard.panel.js
testing/page_objects/wizardpanel/htmlarea.form.panel.js
testing/page_objects/wizardpanel/liveform/page.components.view.js
testing/specs/content-types/custom.selector0_2.spec.js
testing/specs/content-types/htmlarea.cke.toolbar.spec.js
testing/specs/page-editor/fragment.save.detach.spec.js
testing/specs/page-editor/image.component.default.caption.spec.js
testing/specs/page-editor/image.component.inspect.panel.spec.js
testing/specs/page-editor/insert.part.htmlarea.spec.js
testing/specs/page-editor/wizard.image.fragment.spec.js
testing/specs/wizard.detailspanel.inbound.outbound.spec.js

verifies bug:  Tooltip is missing for the 'Hide Component View' icon

ui-tests issue#1109 + update tests

---

src/main/resources/assets/js/app/inputtype/ui/text/HtmlEditor.ts
src/main/resources/assets/lib/ckeditor/plugins/image2/plugin.js

-Adjusted image's plugin to detect which elements to be upcasted to an image widget (excluded standalone img tags)
-Removed one of two code modifications of image plugin

Multiple issues when pasting an image into HTML Editor #1093

---

build.gradle
src/main/resources/admin/tools/main/main.html
src/main/resources/com/enonic/xp/app/contentstudio/liveEditBodyEnd.html
src/test/resources/com/enonic/xp/app/contentstudio/liveEditInjectionBodyEnd.html
webpack.config.js

* Added chunks splitting and moved common code to separate files.

Update minification process of the production build #1137

---

testing/libs/app_const.js
testing/specs/content.workflow.state.spec.js
testing/specs/publish/content.publish.dialog.spec.js
testing/specs/publish/wizard.schedule.spec.js
testing/specs/save.folder.failed.attempt.spec.js
testing/specs/site.configurator.required.input.spec.js

verifies issue "Save button should remain enabled after failed attempt to save a content"

ui-tests - issue#1034

---

src/main/resources/assets/js/app/create/NewContentDialog.ts
src/main/resources/assets/js/app/dialog/BasePublishDialog.ts
src/main/resources/assets/js/app/inputtype/siteconfigurator/SiteConfiguratorSelectedOptionView.ts
src/main/resources/assets/js/app/inputtype/ui/siteconfigurator/SiteConfiguratorDialog.ts
src/main/resources/assets/js/app/inputtype/ui/text/dialog/HTMLAreaDialogHandler.ts
src/main/resources/assets/js/app/issue/IssueDialogsManager.ts
src/main/resources/assets/js/app/issue/view/IssueDetailsDialog.ts
src/main/resources/assets/js/app/issue/view/IssueDialog.ts
src/main/resources/assets/js/app/issue/view/IssueListDialog.ts
src/main/resources/assets/styles/dialog/site-configurator-dialog.less
src/main/resources/assets/styles/main.less

-Masking SiteConfiguratorDialog when any dialog is being opened while SiteConfiguratorDialog is open, that will make modal dialog focus handlers work correctly and solve described issues
-Updated dialogs to use isOpen() instead of isVisible()

Incorrect confirmation behaviour in site config with an item-set #1226

---

src/main/resources/assets/js/app/issue/view/IssueDetailsDialog.ts

-Scrolling list dialog body to the bottom when comment list items loaded (or new comment added) and item views rendered

Scroll the list of issue comments to the bottom #1167

---

src/main/resources/assets/js/app/dialog/BasePublishDialog.ts

…ould be cleared after changing a selection #1199

Publish Content dialog - Validation messages should be reset when the dialog is reopened

---

src/main/resources/assets/js/app/wizard/ContentWizardPanel.ts
src/main/resources/assets/js/app/wizard/ContentWizardToolbarPublishControls.ts
src/main/resources/assets/js/app/wizard/action/ContentWizardActions.ts
src/main/resources/assets/styles/browse/content-publish-menu-button.less
src/main/resources/assets/styles/wizard/content-wizard-panel.less
src/main/resources/assets/styles/wizard/content-wizard-toolbar.less

* Removed mobile publish action.
* Updated mobile publish controls management, adding "mark as ready" control.
* Added publish dropdown for mobile resolution.

Content Wizard - publish menu is not visible in mobile resolution #1142

---

src/main/resources/assets/js/app/issue/view/IssuesPanel.ts

…ed issue has been reopened #1233
-Switching between open/closed issues automatically when issues get updated

The list of issues is not updated after a closed issue has been reopened

---

src/main/resources/assets/js/app/publish/ContentPublishDialog.ts

Publish Tree only includes children of the first selected item

---

src/main/resources/assets/js/app/browse/ContentBrowsePanel.ts
src/main/resources/assets/js/app/browse/ContentTreeGrid.ts
src/main/resources/assets/js/app/browse/filter/ContentBrowseFilterPanel.ts
src/main/resources/assets/js/app/dialog/DialogTogglableItemList.ts
src/main/resources/assets/js/app/event/ContentServerEventsHandler.ts
src/main/resources/assets/js/app/inputtype/ui/selector/ContentInputTypeManagingAdd.ts
src/main/resources/assets/js/app/publish/PublishDialogDependantList.ts
src/main/resources/assets/js/app/view/context/ContextView.ts
src/main/resources/assets/js/app/view/context/widget/details/PageTemplateWidgetItemView.ts
src/main/resources/assets/js/app/wizard/ContentWizardPanel.ts
src/main/resources/assets/js/app/wizard/page/LiveFormPanel.ts
src/main/resources/assets/js/app/wizard/page/contextwindow/inspect/page/PageTemplateAndControllerSelector.ts

-Won't fetch all content summaries after permissions updated, only those that are required

Batched resolvedByIds #1285

---

src/main/resources/assets/js/app/inputtype/ui/text/HtmlEditor.ts

-Issue origin: image widget plugin wraps figure element that is centered with alignment
-Solved by overriding required function in image plugin code

Centered images in HTML Area become left-aligned in edit mode #1289

---

src/main/resources/assets/js/page-editor/Highlighter.ts

Validate and escape all unsafe data passed to fromString method

---

build.gradle

Added bnd configuration to prevent dev folder from appearing in the bundle.

Remove Dev folder from bundle

---

testing/libs/studio.utils.js
testing/specs/page-editor/fragment.move.spec.js

ui-tests #1473

---

src/main/resources/assets/js/app/ContentAppContainer.ts
src/main/resources/assets/js/app/bar/ContentAppBar.ts
src/main/resources/assets/js/app/settings/SettingsAppPanel.ts

-Switching to a default project when current project deleted

Name of deleted project remains in Project Selector #1466

---

src/main/resources/assets/js/app/inputtype/ui/upload/AttachmentItem.ts
src/main/resources/assets/js/app/inputtype/ui/upload/AttachmentUploaderEl.ts
src/main/resources/assets/js/app/inputtype/ui/upload/MediaUploaderEl.ts
src/main/resources/assets/js/app/resource/XDataResourceRequest.ts
src/main/resources/assets/js/app/util/ImageUrlResolver.ts
src/main/resources/assets/js/app/util/UrlHelper.ts
src/main/resources/assets/js/app/view/ContentItemPreviewPanel.ts
src/main/resources/assets/js/app/view/context/widget/details/AttachmentsWidgetItemView.ts
src/main/resources/assets/js/app/wizard/ProjectBasedResourceRequest.ts
src/main/resources/assets/js/app/wizard/ThumbnailUploaderEl.ts

-Added static 'base' layer into backend requests path,  .../<project>/<layer>/...
Requires https://github.com/enonic/xp/pull/7864 to be merged

Projects: add default layer to the requests #1480

---

src/main/resources/assets/js/app/settings/event/SettingsServerEvent.ts

-Filtering settings app events by repo 'com.enonic.cms.'

Exception when a new non-CMS repository is created #1478

---

testing/page_objects/wizardpanel/liveform/page.components.view.js
testing/specs/content-types/htmlarea2_4.cke.spec.js
testing/specs/image.wizard.rotate.revert.spec.js
testing/specs/page-editor/insert.part.htmlarea.spec.js

this test verifies - Part description is not shown when the part is included more than once #1474

ui-tests - issue#1486

---

src/main/resources/assets/js/app/security/Access.ts
src/main/resources/assets/js/app/security/AccessChangedEvent.ts
src/main/resources/assets/js/app/security/AccessSelector.ts
src/main/resources/assets/js/app/security/UserAccessListItemView.ts
src/main/resources/assets/js/app/view/AccessControlEntryView.ts
src/main/resources/assets/js/main.ts
src/main/resources/i18n/phrases.properties

Small fixes:
-Fixed Access selector to display localized access options
-Not showing notification when current project is not available, just silently switching to first available project

Epic project small fi

---

src/main/resources/assets/js/app/wizard/ContentWizardToolbar.ts

-missing default icon fallback option

Project icon is missing in the Content Wizard #1533

---

src/main/resources/assets/js/app/ContentVersion.ts
src/main/resources/assets/js/app/content/CompareStatus.ts
src/main/resources/assets/js/app/content/ContentSummaryAndCompareStatus.ts
src/main/resources/assets/js/app/publish/PublishStatus.ts
src/main/resources/assets/js/app/rendering/UriHelper.ts
src/main/resources/assets/js/app/versioning/Branch.ts
src/main/resources/assets/js/app/view/context/widget/version/VersionsView.ts
src/main/resources/assets/styles/view/context/widget-version.less

-Updated status Published (Pending) to be displayed with other color and right caption

Incorrect status in version history when republishing content. #941

---

src/main/resources/admin/tools/main/main.html
src/main/resources/admin/tools/main/main.js
src/main/resources/admin/tools/settings/settings.js
src/main/resources/assets/js/app/view/context/WidgetItemView.ts

-Using project context to set coorect repo url
-Removed 'repository' from CONFIG object as current repo may be changed

Content Project - Widget called with incorrect repository key #1550

---

src/main/resources/assets/js/app/wizard/ContentWizardPanel.ts

-Removed preview button visibility check on setting live edit, updateButtonState() on layout is supposed to be enough

Fragment Wizard - Preview button should be visible in the toolbar #1384

---

src/main/resources/assets/js/app/browse/ContentBrowsePanel.ts
src/main/resources/assets/js/app/browse/filter/ContentBrowseFilterPanel.ts
src/main/resources/assets/js/app/dialog/DialogTogglableItemList.ts
src/main/resources/assets/js/app/event/AggregatedServerEventsListener.ts
src/main/resources/assets/js/app/event/BatchContentServerEvent.ts
src/main/resources/assets/js/app/event/ContentServerChange.ts
src/main/resources/assets/js/app/event/ContentServerChangeItem.ts
src/main/resources/assets/js/app/event/ContentServerEvent.ts
src/main/resources/assets/js/app/event/ContentServerEventsHandler.ts
src/main/resources/assets/js/app/event/ContentServerEventsTranslator.ts
src/main/resources/assets/js/app/event/IssueServerChange.ts
src/main/resources/assets/js/app/event/IssueServerChangeItem.ts
src/main/resources/assets/js/app/event/IssueServerEvent.ts
src/main/resources/assets/js/app/inputtype/ui/selector/ContentInputTypeManagingAdd.ts
src/main/resources/assets/js/app/issue/event/IssueServerEventsHandler.ts
src/main/resources/assets/js/app/publish/PublishDialogDependantList.ts
src/main/resources/assets/js/app/publish/PublishDialogItemList.ts
src/main/resources/assets/js/app/settings/event/SettingsServerChange.ts
src/main/resources/assets/js/app/settings/event/SettingsServerChangeItem.ts
src/main/resources/assets/js/app/settings/event/SettingsServerEvent.ts
src/main/resources/assets/js/app/view/context/widget/details/PageTemplateWidgetItemView.ts
src/main/resources/assets/js/app/wizard/page/contextwindow/inspect/page/PageTemplateAndControllerSelector.ts

-Moved ContentServerEvent and IssueServer event with related classes into app-cs
-Adjusted server event classes to be compatible with parent ones in lib-admin-ui
-Added ContentServerEventsTranslator to convert EventJson to ContentServerEvent and IssueServer
-Filtering out content and issue CRUD events from non current project repo

Projects: filter node server events from other projects/repos #1578

---

src/main/resources/assets/js/app/settings/wizard/ProjectItemNameWizardStepForm.ts
src/main/resources/assets/js/app/settings/wizard/ProjectReadAccessWizardStepForm.ts
src/main/resources/assets/js/app/settings/wizard/ProjectWizardPanel.ts

-system.admin, system.everyone and cms.admin are roles and all roles are filtered anyway by restricting allowed principal types

Filter options in the principal selector #1587

---

src/main/resources/assets/js/app/settings/wizard/ProjectItemNameWizardStepForm.ts
src/main/resources/assets/js/app/settings/wizard/SettingsDataItemWizardPanel.ts

-If trying to close project wizard with invalid data then validating form items and showing errors

Refactor usage of save confirmation dialog #1646

---

src/main/resources/assets/js/app/settings/wizard/SettingsDataItemWizardPanel.ts

name block is not used in project wizard header

---

src/main/resources/assets/js/app/settings/SettingsAppPanel.ts

…t #1627
-Listening update event that will be spawned after project create and checking if item with id is present in grid or not, then adding it if it is missing; otherwise just updating grid item and opened wizard

New project doesn't show up in the Settings grid after save

---

src/main/resources/assets/js/app/settings/SettingsAppContainer.ts
src/main/resources/assets/js/app/wizard/ContentWizardPanel.ts
src/main/resources/assets/js/main.ts

-Starting settings (project) event listener in main.ts since now it is required in many places

Content Wizard panels should be automatically closed when the project is deleted

---

testing/page_objects/browsepanel/detailspanel/content.widget.item.view.js
testing/specs/browse.panel.properties.widget.spec.js
testing/specs/project/create.content.in.project.spec.js

Verifies - Details Panel should be cleared after a content has been unselected #1744

ui-tests - issue#1745

---

src/main/resources/assets/js/app/settings/event/SettingsServerEvent.ts
src/main/resources/assets/js/app/settings/event/SettingsServerEventsListener.ts
src/main/resources/assets/js/app/view/context/ContextView.ts
src/main/resources/assets/js/main.ts
src/main/resources/assets/styles/wizard/content-wizard-panel.less
src/main/resources/i18n/phrases.properties

…n new Websocket connection for the Settings events (#1723)

 No error message when there's no connection to Websockets

---

src/main/resources/assets/js/app/wizard/ContentWizardPanel.ts
src/main/resources/assets/styles/themes.less
src/main/resources/assets/styles/wizard/content-wizard-panel.less

-Wizard toolbar styles to be applied without live edit also, thus taking them to the right place

Incorrect layout in Wizard Step Navigator Toolbar #1762

---

src/main/resources/assets/js/app/browse/ContentBrowsePanel.ts
src/main/resources/assets/js/app/browse/ContentTreeGrid.ts
src/main/resources/assets/js/app/settings/browse/SettingsBrowsePanel.ts
src/main/resources/assets/js/app/wizard/PageComponentsView.ts

Requires https://github.com/enonic/lib-admin-ui/pull/1275

Refactoring treegrid usage #1799

---

src/main/resources/assets/js/app/issue/view/InPlaceTextArea.ts
src/main/resources/assets/js/app/issue/view/InPlaceTextInput.ts
src/main/resources/assets/js/app/issue/view/IssueDetailsDialogHeader.ts

For some reason this wasn't done in https://github.com/enonic/app-contentstudio/issues/1205

Escape contents of title and comment fields in the Issue dialog

---

src/main/resources/assets/js/app/settings/wizard/SettingsDataItemWizardPanel.ts

Project Wizard - confirmation about unsaved changes should appear when name input is filled in #1802

---

src/main/resources/assets/styles/browse/sort-content-dialog.less

[IE11] Incorrect content overflow in modal dialogs #1430

---

src/main/resources/assets/js/app/wizard/PageComponentsView.ts
src/main/resources/assets/js/page-editor/ItemViewContextMenu.ts

-Helping IE receive click events

[IE 11] Issues with inserting components in Page Component View #1857

---

testing/page_objects/base.browse.panel.js
testing/page_objects/browsepanel/content.browse.panel.js
testing/page_objects/wizardpanel/htmlarea.form.panel.js
testing/page_objects/wizardpanel/site.configurator.dialog.js
testing/specs/browse.panel.selections.spec.js
testing/specs/browse.selection.controller.spec.js
testing/specs/page-editor/generate.name.for.fragments.spec.js
testing/specs/page-editor/insert.part.htmlarea.spec.js
testing/specs/project/delete.project.in.filtered.grid.spec.js
testing/specs/project/multiselect.in.settings.panel.spec.js

Tests to Verify  https://github.com/enonic/app-contentstudio/issues/1828
Selection Controller is not refreshed after selected projects have been removed

ui-tests issue#1829 + code cleanup

---

src/main/resources/assets/js/app/settings/wizard/ProjectRolesWizardStepForm.ts

Requires https://github.com/enonic/lib-admin-ui/pull/1320

Project Wizard form scrolled down after icon upload #1886

---

testing/page_objects/base.browse.panel.js
testing/page_objects/browsepanel/content.browse.panel.js
testing/page_objects/project/settings.browse.panel.js
testing/specs/project/change.access.mode.spec.js
testing/specs/project/edit.project.spec.js
testing/specs/project/project.wizard.access.roles.spec.js
testing/specs/project/settings.browse.panel.context.menu.spec.js

New test + fixes for failed tests

Issue 1932

---

src/main/resources/assets/js/app/create/MostPopularItemsList.ts

…Owner() ) );
-filtering null values

Error in console after opening New Content Dialog by user with Editor or Author roles

---

src/main/resources/assets/js/app/inputtype/ui/selector/image/ImageEditor.ts
src/main/resources/assets/js/app/inputtype/ui/selector/image/ImageUploaderEl.ts
src/main/resources/assets/js/app/inputtype/upload/ImageUploader.ts

Wait with loading an image in Image Editor until Image Uploader is rendered when it's possible to calculate dimensions of the placeholder (#1975)

Placeholder is not shown while image is being loaded in the Image Editor

---

src/main/resources/assets/js/app/settings/wizard/panel/form/ProjectReadAccessWizardStepForm.ts
src/main/resources/assets/js/app/settings/wizard/panel/form/ProjectRolesWizardStepForm.ts

Requires https://github.com/enonic/lib-admin-ui/pull/1395

Subproject wizard - issues with 'Copy' buttons #2076

---

src/main/resources/assets/js/app/wizard/page/contextwindow/inspect/page/PageTemplateAndControllerSelector.ts

-selector was not setting right value after reload

Selected page controller is not displayed in the Inspect Panel #2001

---

src/main/resources/assets/js/app/settings/wizard/panel/SettingsDataItemWizardPanel.ts

Validating wizard forms when not valid

New Project Wizard doesn't show confirmation about unsaved changes #1961

---

src/main/resources/assets/js/app/browse/ContentTreeGrid.ts
src/main/resources/assets/styles/browse/content-tree-grid.less

Requires https://github.com/enonic/lib-admin-ui/pull/1445

Apply styling based on new inherited state #2237

---

src/main/resources/assets/styles/dialog/site-configurator-dialog.less

`site.xml` to test with:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<site>
<form>
<input type="TextLine" name="text1">
<label>text1</label>
<occurrences minimum="1" maximum="1" />
</input>
<field-set>
<label>123</label>
<items>
<input type="TextLine" name="text2">
<label>text2</label>
<occurrences minimum="1" maximum="1" />
</input>
</items>
</field-set>
<field-set>
<label>123</label>
<items>
<input type="TextLine" name="text3">
<label>text3</label>
<occurrences minimum="1" maximum="1" />
</input>
</items>
</field-set>
<field-set>
<label>123</label>
<items>
<input type="TextLine" name="text4">
<label>text4</label>
<occurrences minimum="1" maximum="1" />
</input>
</items>
</field-set>
<field-set>
<label>123</label>
<items>
<input type="TextLine" name="text5">
<label>text5</label> …
```

Elements are not rendered inside long site config form

---

src/main/resources/assets/js/app/view/context/ContextView.ts

-Have to set default widget as active after removing layers widget

Details widget does not load after context switch #2270

---

src/main/resources/assets/js/app/ContentFormContext.ts

Required for https://github.com/enonic/lib-admin-ui/pull/1501

ContentFormContext: move FormState to lib-admin-ui.FormContext #2377

---

src/main/resources/assets/js/app/project/tree/LayersContentTreeList.ts
src/main/resources/assets/js/app/view/context/widget/layers/LayerContentView.ts
src/main/resources/assets/js/app/view/context/widget/layers/LayerContentViewDataBlock.ts
src/main/resources/assets/styles/main.less
src/main/resources/assets/styles/project/layer-content-view-data.less
src/main/resources/assets/styles/settings/dialog/layers-content-tree-dialog.less
src/main/resources/assets/styles/view/context/widget-layers.less

-moved common things into LayerContentViewDataBlock.ts

Improvements to LayersContentTreeDialog #2400

---

src/main/resources/assets/js/app/browse/ContentBrowsePanel.ts
src/main/resources/assets/js/app/browse/ContentTreeGrid.ts

-updates for content treegrid add/delete operations
Requires https://github.com/enonic/lib-admin-ui/pull/1548

Grid is not refreshed after adding/deleting content #2436

---

src/main/resources/assets/js/app/wizard/ContentWizardHeader.ts

-performing uniqueness check after last ongoing request returned
If not enough I can add a spinner while check is performed and disable Save action during that.

Blinking message after a path has been updated in wizard. #2442

---

src/main/resources/assets/js/app/inputtype/ui/selector/image/ImageContentComboBox.ts
src/main/resources/assets/styles/inputtype/selector/image/image-content-combo-box.less

<hideToggleIcon> in Image Selector config breaks the layout

---

src/main/resources/assets/js/app/view/context/ContextView.ts
src/main/resources/assets/js/app/view/context/widget/layers/LayersWidgetItemView.ts

-reloading dialog on create/update/delete

LayersContentTree Dialog is not refreshed after updating content #2258

---

testing/libs/studio.utils.js
testing/page_objects/wizardpanel/content.wizard.panel.js
testing/specs/update.path.spec.js

tests to verify https://github.com/enonic/app-contentstudio/issues/2498

ui-tests for updating of content path issue#2499

---

src/main/resources/assets/js/app/ContentAppPanel.ts
src/main/resources/assets/js/app/settings/dialog/ProjectSelectionDialog.ts

Requires https://github.com/enonic/lib-admin-ui/pull/1636

ContentAppPanel: bind app panel keys only after project set #2624

---

src/main/resources/assets/js/app/AppContainerFactory.ts
src/main/resources/assets/js/app/AppContext.ts
src/main/resources/assets/js/app/AppWrapper.ts
src/main/resources/assets/js/app/ContentAppContainer.ts
src/main/resources/assets/js/app/MainAppContainer.ts
src/main/resources/assets/js/app/settings/SettingsAppContainer.ts
src/main/resources/assets/js/app/settings/SettingsAppPanel.ts
src/main/resources/assets/js/app/settings/browse/SettingsBrowsePanel.ts
src/main/resources/assets/js/app/settings/grid/SettingsItemsTreeGrid.ts
src/main/resources/assets/js/app/settings/grid/SettingsTreeGridActions.ts
src/main/resources/assets/js/app/settings/wizard/action/ProjectWizardActions.ts
src/main/resources/assets/js/app/settings/wizard/panel/ProjectWizardPanel.ts
src/main/resources/assets/styles/project/project-list.less

-Creating app containers (main or settings) only on demand
-More generic app containers
-Skipping redundant server requests

Project list is fetched on every change in Project Wizard form #2627

---

src/main/resources/assets/js/app/wizard/ContentWizardPanel.ts
src/main/resources/assets/js/app/wizard/action/BasePublishAction.ts
src/main/resources/assets/js/app/wizard/action/PublishAction.ts
src/main/resources/assets/js/app/wizard/action/RequestPublishAction.ts
src/main/resources/assets/styles/publish/base-publish-dialog.less
src/main/resources/i18n/phrases.properties
src/main/resources/i18n/phrases_be.properties
src/main/resources/i18n/phrases_es.properties
src/main/resources/i18n/phrases_fr.properties
src/main/resources/i18n/phrases_it.properties
src/main/resources/i18n/phrases_nl.properties
src/main/resources/i18n/phrases_no.properties
src/main/resources/i18n/phrases_pl.properties
src/main/resources/i18n/phrases_pt.properties
src/main/resources/i18n/phrases_ru.properties
src/main/resources/i18n/phrases_sv.properties

Remove auto-marking of items as ready #2640

---

src/main/resources/assets/js/app/resource/GetDescendantsOfContentsRequest.ts

-Correctly setting enum params in request

Unpublish dialog incorrectly fetches child items #2684

---

src/main/resources/assets/js/app/settings/browse/SettingsBrowsePanel.ts
src/main/resources/assets/js/app/settings/browse/action/DeleteSettingsItemAction.ts
src/main/resources/assets/js/app/settings/browse/action/SyncAction.ts
src/main/resources/assets/js/app/settings/grid/SettingsTreeGridActions.ts
src/main/resources/assets/js/app/settings/resource/ProjectResourceRequest.ts
src/main/resources/assets/js/app/settings/resource/SyncLayersRequest.ts
src/main/resources/i18n/phrases.properties

Requires https://github.com/enonic/lib-admin-ui/pull/1659

Implement manual syncing of layer data #2678

---

src/main/resources/assets/js/app/dialog/DependantItemsDialog.ts

-Using action to set label so label is preserved on button update

Unpublish button is missing the number of items #2691

---

src/main/resources/assets/js/app/publish/ContentPublishDialog.ts

Requires https://github.com/enonic/lib-admin-ui/pull/1690

Publish Wizard - dialog should get focus when the dialog opens. #2636

---

src/main/resources/assets/js/app/browse/action/PreviewContentAction.ts

Temp fix for release,
main fix is in https://github.com/enonic/app-contentstudio/pull/2713

Preview button is disabled for a site with controller #2646

---

src/main/resources/assets/js/app/wizard/XDataWizardStepForm.ts

-forcing xdata validation on layout to trigger validation change listeners

ContentWizard - Incorrect validation inside X-data #2751

---

src/main/resources/assets/js/app/inputtype/ui/text/HtmlEditor.ts
src/main/resources/assets/js/app/inputtype/ui/text/dialog/TableDialog.ts

-removed deprecated align attribute

Remove align attribute on table #2596

---

modules/lib/package-lock.json
package-lock.json
src/main/resources/assets/js/app/wizard/page/LiveEditPageProxy.ts

-using DOMPurify to sanitize loaded html

LiveEditPageProxy loads component in the unsafe way #1416
